config/routes.rb
Att::Application.routes.draw do

  resources :payroll_reports

  resources :punches

  resources :payrolls do 
    resources :slips
    resources :employees
    member do
     get 'get_employee_hours'
    end
  end
	
  resources :employees do
	  resources :payroll_records do 
			collection do
				get 'report'
			end
		end
	
    member do
     get 'set_current'
    end
  end
  
  resources :stores do
    member do
     get 'set_current'
    end
  end

  resources :posts do
    resources :comments
  end

  scope :api do
    get "/payrolls(.:format)" => "payrolls#index"
    get "/payrolls/:id(.:format)" => "payrolls#show"
    post "/payrolls(.:format)" => "payrolls#create"
		put "/payrolls/:id(.:format)" => "payrolls#update"
    delete "/payrolls/:id(.:format)" => "payrolls#destroy"

    get "/employees(.:format)" => "employees#index"
    get "/employees/:id(.:format)" => "employees#show"
    
    get "/punches(.:format)" => "punches#index"
    get "/punches/:id(.:format)" => "punches#show"
  end

  root 'stores#index'
  

  

end

app/models/employee.rb
class Employee
  include Mongoid::Document
  include Mongoid::Timestamps  
  include Mongoid::Paperclip
  
  belongs_to :store
  has_many :punches
  has_many :slips  
  has_many :payroll_records  
  
  field :num, type: String    
  field :barcode, type: String      
  field :name, type: String
  field :name_cn, type: String
  field :gender, type: Boolean
  field :dob, type: Date
  field :soe, type: Date
  field :eoe, type: Date
  
  field :sin, type: String    
  field :dln, type: String    
  field :ohc, type: String      
  
  field :address, type: String    
  field :city, type: String    
  field :provence, type: String      
  field :postal, type: String      
  
  field :home_phone, type: String    
  field :cell_phone, type: String      
  
  field :department, type: String        
  field :position, type: String, default: 'Employee'
  
  field :rate, type: Float

  field :active, type: Boolean, default: 1
  
  field :status, type: String, default: 'out'
  
  field :manager_id, type: Integer, default: 0
  
  field :notes, type: String  
  field :oid, type: Integer
  
  has_mongoid_attached_file :photo
  
  def in?(tm)
    self.payroll_records.each do |pr|
      if pr.in1<tm and pr.out1>tm then
        return true 
      end
    end
    return false
  end
  
  def get_work_hours(start_date, end_date)
    wh = 0
		last_checkin = nil
    
		self.punches.and({:time.gt => start_date}, {:time.lt => end_date}).order_by(:time.asc).each do |punch|
			if punch.action == 'checkin' then
				last_checkin = punch.time
			elsif punch.action == 'checkout' then
				wh = wh + (punch.time - last_checkin) * 1.day.seconds / 1.hour.seconds.to_f
			end
		end
		return (wh*100).to_i/100.0
  end

	def payroll_report(start_dt, end_dt, print_tm=nil)
		payroll_records = self.payroll_records.where(:date => { "$lte" => end_dt, "$gte" => start_dt }).order_by(:date.asc)
		
		grand_total = 0
		grand_total_meal = 0
		grand_total_holiday = 0
		payroll_records.each do |pr|
			grand_total = grand_total + pr.total
			grand_total_meal = grand_total_meal + pr.meal
			grand_total_holiday = grand_total_holiday + pr.holiday
		end
		
		template_file = "template1.odt"
		
		report = ODFReport::Report.new(template_file) do |r|
			print_tm = Time.now if print_tm==nil
			r.add_field :report_time, print_tm.strftime("%d/%m/%Y  %l:%M %p")
			r.add_field :employee_name, self.name
			r.add_field :employee_no, self.num
			r.add_field :department, self.department
			r.add_field :start_dt, start_dt.strftime("%d/%m/%Y")
			r.add_field :end_dt, end_dt.strftime("%d/%m/%Y")
			
			r.add_table("PAYROLL", payroll_records, :header=>true) do |t|
				t.add_column(:date) {|pr| pr.date.strftime("%d/%m/%Y %a")}
				t.add_column(:in1) {|pr| pr.in1 != nil ? pr.in1.strftime("%l:%M %p") : ''}
				t.add_column(:out1) {|pr| pr.out1 != nil ? pr.out1.strftime("%l:%M %p") : ''}

				t.add_column(:meal, :meal)
				t.add_column(:overtime, :overtime)
				t.add_column(:sick, :sick)
				t.add_column(:holiday){|pr| pr.holiday.round(2)}
				t.add_column(:other, :other)
							
				t.add_column(:total, :total)
			end
			
			r.add_field :grand_total, grand_total.round(2)
			r.add_field :total_meal, grand_total_meal.round(2)
			r.add_field :total_holiday, grand_total_holiday.round(2)
		end

		odt_file = report.generate
		puts odt_file
		pdf_file = "/tmp/template1.pdf"
		if File.exist?(pdf_file) then
			`rm #{pdf_file}`
		end
		
		puts "libreoffice --headless --invisible --convert-to pdf #{odt_file} --outdir /tmp"
		`libreoffice --headless --invisible --convert-to pdf #{odt_file} --outdir /tmp`

		return pdf_file
	end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    if params[:payroll_id] != nil then
      @payroll = Payroll.find(params[:payroll_id])
      @employees = @payroll.employees
    else
      @start_date = params[:start_date] if params[:start_date] != nil
      @end_date = params[:end_date] if params[:end_date] != nil
      @employees = @store.employees
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    @employee.store = @store
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:num, :name, :sin, :rate, :photo, :department)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee, :html => { :multipart => true }) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% [:num, :name, :sin, :rate, :department].each do |attr| %>
    <div class="field">
      <%= f.label attr %><br>
      <%= f.text_field attr %>
    </div>
  <% end %>

  <%= f.file_field :photo %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1><%=@employees.length%> employees</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.name, employee %></td>
        <td><%= link_to 'Payroll', employee_payroll_records_path(employee)%></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%=@employee.num %>
<%=@employee.name %>
<%=image_tag(@employee.photo.url) %>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

<div ng-app="employeeApp">
  <div ng-controller="employeeCtrl">
  
  </div>
</div>