config/routes.rb
Att::Application.routes.draw do

  resources :payroll_reports

  resources :punches

  resources :payrolls do 
    resources :slips
    resources :employees
    member do
     get 'get_employee_hours'
    end
  end
	
  resources :employees do
	  resources :payroll_records do 
			collection do
				get 'report'
			end
		end
	
    member do
     get 'set_current'
    end
  end
  
  resources :stores do
    member do
     get 'set_current'
    end
  end

  resources :posts do
    resources :comments
  end

  scope :api do
    get "/payrolls(.:format)" => "payrolls#index"
    get "/payrolls/:id(.:format)" => "payrolls#show"
    post "/payrolls(.:format)" => "payrolls#create"
		put "/payrolls/:id(.:format)" => "payrolls#update"
    delete "/payrolls/:id(.:format)" => "payrolls#destroy"

    get "/employees(.:format)" => "employees#index"
    get "/employees/:id(.:format)" => "employees#show"
    
    get "/punches(.:format)" => "punches#index"
    get "/punches/:id(.:format)" => "punches#show"
  end

  root 'stores#index'
  

  

end

app/models/store.rb
class Store
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :employees
  
  field :name, type: String  
  field :full_name, type: String    
  field :address, type: String      
  field :phone, type: String        
  field :fax, type: String          
  field :num, type: Integer
  field :oid, type: Integer
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy, :set_current]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  def set_current
    cookies.permanent[:current_store] = @store.name
    respond_to do |format|
      format.html { render text: "OK"}
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :num)      
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :num %><br>
    <%= f.text_field :num %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<table class="table table-striped table-bordered table-condensed">
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store %></td>
        <td>
          <%= link_to 'Edit', edit_store_path(store), class: "btn btn-primary" %> 
          <%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
        <td>
          <%= link_to 'Employees', employees_path, class: "btn btn-primary" %>
          <%= link_to 'Payroll', payrolls_path, class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/set_current.js.erb
//$('#current_store').dropdown('toggle').html('<%=@store.name%> <b class="caret">');
location.reload();

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>