config/routes.rb
Att::Application.routes.draw do

  resources :payroll_reports

  resources :punches

  resources :payrolls do 
    resources :slips
    resources :employees
    member do
     get 'get_employee_hours'
    end
  end
	
  resources :employees do
	  resources :payroll_records do 
			collection do
				get 'report'
			end
		end
	
    member do
     get 'set_current'
    end
  end
  
  resources :stores do
    member do
     get 'set_current'
    end
  end

  resources :posts do
    resources :comments
  end

  scope :api do
    get "/payrolls(.:format)" => "payrolls#index"
    get "/payrolls/:id(.:format)" => "payrolls#show"
    post "/payrolls(.:format)" => "payrolls#create"
		put "/payrolls/:id(.:format)" => "payrolls#update"
    delete "/payrolls/:id(.:format)" => "payrolls#destroy"

    get "/employees(.:format)" => "employees#index"
    get "/employees/:id(.:format)" => "employees#show"
    
    get "/punches(.:format)" => "punches#index"
    get "/punches/:id(.:format)" => "punches#show"
  end

  root 'stores#index'
  

  

end

app/models/slip.rb
class Slip
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  belongs_to :employee
  belongs_to :payroll
  accepts_nested_attributes_for :payroll
  
  field :work_hours, type: Float, default: 0
	field :notes, type: String
  field :punches, type: Array  

  def r_work_hours
    return 0 if self.employee == nil or self.payroll == nil
    wh = 0
		last_checkin = nil
    
		self.punches.each do |punch|
			if punch['action'] == 'checkin' then
				last_checkin = punch['time'].to_i
			elsif punch['action'] == 'checkout' then
				wh = wh + (punch['time'].to_i - last_checkin)
			end
		end
		return wh/3600.0
  end

  after_create do
    if self.employee != nil and self.payroll != nil then
      self.employee.punches.and({:time.gt => self.payroll.start_date}, {:time.lt => self.payroll.end_date}).each do |punch|
        self.punches = [] if self.punches == nil
        self.punches.push({:time=>punch.time.to_i, :action=>punch.action})
      end
      self.save
      self.reload
    end
  end
end

app/controllers/slips_controller.rb
class SlipsController < ApplicationController
  before_action :load_payroll  
  before_action :set_slip, only: [:show, :edit, :update, :destroy]

  # GET /slips
  # GET /slips.json
  def index
    @slips = @payroll.slips
  end

  # GET /slips/1
  # GET /slips/1.json
  def show
  end

  # GET /slips/new
  def new
    @slip = Slip.new
  end

  # GET /slips/1/edit
  def edit
  end

  # POST /slips
  # POST /slips.json
  def create
    @payroll = Payroll.find(params[:payroll_id])
    @slip = Slip.new(slip_params)
    respond_to do |format|
      if @slip.save
        format.html { redirect_to [@payroll, @slip], notice: 'Slip was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@payroll, @slip] }
      else
        format.html { render action: 'new' }
        format.json { render json: @slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slips/1
  # PATCH/PUT /slips/1.json
  def update
    respond_to do |format|
      if @slip.update(slip_params)
        format.html { redirect_to [@payroll, @slip], notice: 'Slip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slips/1
  # DELETE /slips/1.json
  def destroy
    @slip.destroy
    respond_to do |format|
      format.html { redirect_to payroll_slips_url(@payroll) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slip
      @slip = Slip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slip_params
      params.require(:slip).permit(:start_date, :payroll_id, :employee_id)
    end
    
    def load_payroll
      @payroll = Payroll.find(params[:payroll_id])
    end    
    
end

app/helpers/slips_helper.rb
module SlipsHelper
end

app/views/slips/_form.html.erb
<%= form_for([@payroll, @slip]) do |f| %>
  <% if @slip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slip.errors.count, "error") %> prohibited this slip from being saved:</h2>

      <ul>
      <% @slip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slips/edit.html.erb
<h1>Editing slip</h1>

<%= render 'form' %>

<%= link_to 'Show', payroll_slip_path(@payroll, @slip) %> |
<%= link_to 'Back', payroll_slips_path(@payroll) %>



<%= link_to 'Show', post_comment_path(@post, @comment) %> |
<%= link_to 'Back', post_comments_path(@post) %>

app/views/slips/index.html.erb
<h1>Listing slips</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @slips.each do |slip| %>
      <tr>
        <td><%= link_to 'Show', payroll_slip_path(@payroll, slip) %></td>
        <td><%= link_to 'Edit', edit_payroll_slip_path(@payroll, slip) %></td>
        <td><%= link_to 'Destroy', [@payroll, slip], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slip', new_payroll_slip_path(@payroll) %>

app/views/slips/new.html.erb
<h1>New slip</h1>

<%= render 'form' %>

<%= link_to 'Back', payroll_slips_path(@payroll) %>

app/views/slips/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payroll_slip_path(@payroll, @slip) %> |
<%= link_to 'Back', payroll_slips_path(@payroll) %>