config/routes.rb
Att::Application.routes.draw do

  resources :payroll_reports

  resources :punches

  resources :payrolls do 
    resources :slips
    resources :employees
    member do
     get 'get_employee_hours'
    end
  end
	
  resources :employees do
	  resources :payroll_records do 
			collection do
				get 'report'
			end
		end
	
    member do
     get 'set_current'
    end
  end
  
  resources :stores do
    member do
     get 'set_current'
    end
  end

  resources :posts do
    resources :comments
  end

  scope :api do
    get "/payrolls(.:format)" => "payrolls#index"
    get "/payrolls/:id(.:format)" => "payrolls#show"
    post "/payrolls(.:format)" => "payrolls#create"
		put "/payrolls/:id(.:format)" => "payrolls#update"
    delete "/payrolls/:id(.:format)" => "payrolls#destroy"

    get "/employees(.:format)" => "employees#index"
    get "/employees/:id(.:format)" => "employees#show"
    
    get "/punches(.:format)" => "punches#index"
    get "/punches/:id(.:format)" => "punches#show"
  end

  root 'stores#index'
  

  

end

app/models/payroll_record.rb
class PayrollRecord
  include Mongoid::Document

  belongs_to :employee

	field :date, type: Date

	field :in1, type: Time
	field :out1, type: Time
	
	field :in2, type: Time
	field :out2, type: Time

	field :overtime, type: Float, default: 0
	field :meal, type: Float, default: 0
	field :sick, type: Float, default: 0
	field :other, type: Float, default: 0
	field :holiday, type: Float, default: 0
	field :total, type: Float, default: 0
	
	def cal_total1
		t = 0
		if in1== nil  or out1 == nil then
			t = 0
		elsif in2 == nil  or out2 == nil then
			t = (out1 - in1)/3600.0
			t = t - meal + holiday
		else
			t = ((out1 - in1)+(out2 - in2))/3600.0
			t = t - meal + holiday
		end
		t = (t*4+0.5).to_i/4.0
		return t.round(2)
	end

	def cal_total2
		t = 0
		if in1== nil  or out1 == nil then
			t = 0
		elsif in2 == nil  or out2 == nil then
			t = (out1 - in1)/3600.0
			t = t - meal + holiday
		else
			t = ((out1 - in1)+(out2 - in2))/3600.0
			t = t - meal + holiday
		end
		return t.round(2)
	end


end

app/controllers/payroll_records_controller.rb
class PayrollRecordsController < ApplicationController
	before_action :load_employee
  before_action :set_payroll_record, only: [:show, :edit, :update, :destroy]

  # GET /payroll_records
  # GET /payroll_records.json
  def index
		if params[:date] != nil then
			@dt = Date.parse(params[:date])
			start_dt = @dt.beginning_of_week
			end_dt = @dt.end_of_week
			@payroll_records = @employee.payroll_records.where(:date => { "$lte" => end_dt, "$gte" => start_dt }).order_by(:date.asc)
		else
			@payroll_records = @employee.payroll_records.order_by(:date.asc)
		end
  end
	
  def report
		if params[:date] != nil then
			dt = Date.parse(params[:date])
			start_dt = dt.beginning_of_week
			end_dt = dt.end_of_week
			
			pdf_file = @employee.payroll_report(start_dt, end_dt)

			send_file(pdf_file, :type => 'application/pdf', :disposition => 'attachment', :filename => "report--#{@employee.num}--#{start_dt}--#{end_dt}")
		end
  end

  # GET /payroll_records/1
  # GET /payroll_records/1.json
  def show
  end

  # GET /payroll_records/new
  def new
    @payroll_record = PayrollRecord.new
  end

  # GET /payroll_records/1/edit
  def edit
  end

  # POST /payroll_records
  # POST /payroll_records.json
  def create
    @payroll_record = @employee.payroll_records.build(payroll_record_params)

    respond_to do |format|
      if @payroll_record.save
        format.html { redirect_to [@employee, @payroll_record], notice: 'Payroll record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payroll_record }
      else
        format.html { render action: 'new' }
        format.json { render json: @payroll_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payroll_records/1
  # PATCH/PUT /payroll_records/1.json
  def update
    respond_to do |format|
      if @payroll_record.update(payroll_record_params)
        format.html { redirect_to @payroll_record, notice: 'Payroll record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payroll_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payroll_records/1
  # DELETE /payroll_records/1.json
  def destroy
    @payroll_record.destroy
    respond_to do |format|
      format.html { redirect_to employee_payroll_records_url(@employee) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payroll_record
      @payroll_record = PayrollRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payroll_record_params
			return params.permit(:in1, :out1, :date, :sick, :holiday, :other, :overtime, :meal)
    end
		
    def load_employee
      @employee = Employee.find(params[:employee_id])
    end    

end

app/helpers/payroll_records_helper.rb
module PayrollRecordsHelper
end

app/views/payroll_records/_form.html.erb
<%= form_for([@employee, @payroll_record]) do |f| %>
  <% if @payroll_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payroll_record.errors.count, "error") %> prohibited this payroll_record from being saved:</h2>

      <ul>
      <% @payroll_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
		<%= f.date_select :date%>
		<br/>

		<table>
			<tr><td><%=	f.label :in1 %></td><td><%= f.time_select :in1%></td></tr>
			<tr><td><%=	f.label :out1 %></td><td><%= f.time_select :out1 %></td></tr>
			<tr><td><%=	f.label :overtime %></td><td><%= f.text_field :overtime %></td></tr>
			<tr><td><%=	f.label :meal %></td><td><%= f.text_field :meal %></td></tr>
			<tr><td><%=	f.label :sick %></td><td><%= f.text_field :sick %></td></tr>
			<tr><td><%=	f.label :holiday %></td><td><%= f.text_field :holiday %></td></tr>
			<tr><td><%=	f.label :other %></td><td><%= f.text_field :other %></td></tr>
		</table>

		<br/>
		<%= f.submit %>
  </div>
<% end %>

app/views/payroll_records/edit.html.erb
<h1>Editing payroll_record</h1>

<%= render 'form' %>

<%= link_to 'Show', employee_payroll_record_path(@employee, @payroll_record) %> |
<%= link_to 'Back', employee_payroll_records_path(@employee) %>

<%= link_to 'Show', post_comment_path(@post, @comment) %> |
<%= link_to 'Back', post_comments_path(@post) %>

app/views/payroll_records/index.html.erb
<h1>Name: <%=@employee.name%></h1>
<h1>Emp Num: <%=@employee.num%></h1>
<h1>Department: <%=@employee.department%></h1>

<table border="solid black 1px">
  <thead>
    <tr>
      <th>Date</th>
      <th>In</th>
      <th>Out</th>
      <th>In</th>
      <th>Out</th>
      <th>Overtime</th>
      <th>Meal</th>
      <th>Sick</th>
      <th>Holiday</th>
      <th>Other</th>
      <th>Total</th>
    </tr>
  </thead>

  <tbody>
		<%total = 0%>
    <% @payroll_records.each do |payroll_record| %>
      <tr>
        <td><%= payroll_record.date.strftime("%d/%m/%Y %a") %></td>
        <td><%= payroll_record.in1 != nil ? payroll_record.in1.strftime("%l:%M %p") : '' %></td>
        <td><%= payroll_record.out1 != nil ? payroll_record.out1.strftime("%l:%M %p") : '' %></td>
        <td><%= payroll_record.in2 != nil ? payroll_record.in2.strftime("%l:%M %p") : '' %></td>
        <td><%= payroll_record.out2 != nil ? payroll_record.out2.strftime("%l:%M %p") : '' %></td>
        <td><%= payroll_record.overtime %></td>
        <td><%= payroll_record.meal %></td>
        <td><%= payroll_record.sick %></td>
        <td><%= payroll_record.holiday %></td>
        <td><%= payroll_record.other %></td>
        <td><%= payroll_record.total %></td>
        
				<td><%= link_to 'Show', employee_payroll_record_path(@employee, payroll_record) %></td>
        <td><%= link_to 'Edit', edit_employee_payroll_record_path(@employee, payroll_record) %></td>
        <td><%= link_to 'Destroy', [@employee, payroll_record], method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% total = total + payroll_record.total%>
      </tr>
    <% end %>
		<tr>
		<td>Total</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
			<td></td>
			<td><%=total.round(2)%></td>
		</tr>
  </tbody>
</table>

<br/>
<%= link_to 'Payroll', employee_payroll_records_path(@employee), :id => 'payroll_records' %><%=date_select :date, :date, :default=>@dt%>
<br/>	
<%= link_to 'download', :action=>'report', :date=>@dt, :format=>'pdf'  %>
<br/>
<%= link_to 'New Payroll record', new_employee_payroll_record_path %>
<script>
$(function() {
	$("#payroll_records").on("click", function(event) {
		var y = $("#date_date_1i").val();
		var m = $("#date_date_2i").val();
		var d = $("#date_date_3i").val();
		var href = $("#payroll_records").attr("href");
		$("#payroll_records").attr("href", href+"?date="+y+"-"+m+"-"+d);
	});
});
</script>

app/views/payroll_records/new.html.erb
<h1>New payroll_record</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_payroll_records_path(@employee) %>

app/views/payroll_records/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_payroll_record_path(@employee, @payroll_record) %> |
<%= link_to 'Back', employee_payroll_records_path(@employee) %>